import{a as R,S,i as n}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="50836787-9d290f1c212f5ca84adef07b2",P="https://pixabay.com/api/",B=15;async function p(i,o){const s={key:q,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:B};try{return(await R.get(P,{params:s})).data}catch(t){throw t}}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),c=document.querySelector(".load-more"),M=new S(".gallery a");function L(i){const o=i.map(({webformatURL:s,largeImageURL:t,tags:e,likes:r,views:a,comments:w,downloads:E})=>`
        <li class="gallery-item">
          <div class="card">
            <a href="${t}">
              <img src="${s}" alt="${e}" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${a}</p>
              <p><b>Comments:</b> ${w}</p>
              <p><b>Downloads:</b> ${E}</p>
            </div>
          </div>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){g.innerHTML=""}function b(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}function v(){c.classList.remove("is-hidden"),c.disabled=!1,c.textContent="Load more"}function f(){c.classList.add("is-hidden")}const x=document.querySelector(".form"),H=document.querySelector(".load-more");let d=1,h="",m=0,l=0;x.addEventListener("submit",O);H.addEventListener("click",A);async function O(i){i.preventDefault();const{elements:o}=i.target,s=o["search-text"].value.trim();if(s===""){n.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}h=s,d=1,l=0,$(),f(),b();try{const t=await p(h,d);if(m=t.totalHits,l=t.hits.length,u(),t.hits.length===0){n.error({title:"No Results",message:"No images found. Please try again!",position:"topRight"});return}L(t.hits),l<m?v():n.info({title:"End of Results",message:"You have reached the end of search results.",position:"topRight"})}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),u()}}async function A(){var i;d++,b(),f();try{const o=await p(h,d);L(o.hits),l+=o.hits.length,l<m?v():(n.info({title:"End of Results",message:"You have reached the end of search results.",position:"topRight"}),f());const s=(i=document.querySelector(".gallery"))==null?void 0:i.firstElementChild;if(s){const{height:t}=s.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
