import{a as R,S,i as n}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const M="50836787-9d290f1c212f5ca84adef07b2",q="https://pixabay.com/api/",P=15;async function g(i,o){const r={key:M,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P};try{return(await R.get(q,{params:r})).data}catch(s){throw s}}const y=document.querySelector(".gallery"),L=document.querySelector(".loader"),c=document.querySelector(".load-more"),B=new S(".gallery a");function b(i){const o=i.map(({webformatURL:r,largeImageURL:s,tags:e,likes:t,views:a,comments:h,downloads:v})=>`
        <li class="gallery-item">
          <div class="card">
            <a href="${s}">
              <img src="${r}" alt="${e}" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${t}</p>
              <p><b>Views:</b> ${a}</p>
              <p><b>Comments:</b> ${h}</p>
              <p><b>Downloads:</b> ${v}</p>
            </div>
          </div>
        </li>
      `).join("");y.insertAdjacentHTML("beforeend",o),B.refresh()}function $(){y.innerHTML=""}function w(){L.classList.remove("is-hidden")}function d(){L.classList.add("is-hidden")}function E(){c.classList.remove("is-hidden"),c.disabled=!1,c.textContent="Load more"}function f(){c.classList.add("is-hidden")}const x=document.querySelector(".form"),O=document.querySelector(".load-more");let u=1,m="",p=0,l=0;x.addEventListener("submit",_);O.addEventListener("click",A);async function _(i){i.preventDefault();const{elements:o}=i.target,r=o["search-text"].value.trim();if(r===""){n.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}if(r.length<3){n.error({title:"Error",message:"Search term must be at least 3 characters long!",position:"topRight"});return}m=r,u=1,l=0,$(),f(),w();const s=1e3,e=Date.now();try{const t=await g(m,u);if(p=t.totalHits,l=t.hits.length,t.hits.length===0){n.error({title:"No Results",message:"No images found. Please try again!",position:"topRight"}),d();return}const a=Date.now()-e,h=Math.max(s-a,0);setTimeout(()=>{d(),b(t.hits),l<p?E():n.info({title:"End of Results",message:"You have reached the end of search results.",position:"topRight"})},h)}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),d()}}async function A(){var i;u++,w(),f();try{const o=await g(m,u);b(o.hits),l+=o.hits.length,l<p?E():(n.info({title:"End of Results",message:"You have reached the end of search results.",position:"topRight"}),f());const r=(i=document.querySelector(".gallery"))==null?void 0:i.firstElementChild;if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{d()}}
//# sourceMappingURL=index.js.map
